# Generated by Django 4.2.5 on 2023-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
